-- إيقاف قواعد الأمان (RLS) للسماح للمتصفح بالتحكم المباشر في قاعدة البيانات دون أن يتطلب المستخدم تسجيل الدخول رسمياً
ALTER TABLE departments DISABLE ROW LEVEL SECURITY;
ALTER TABLE employees DISABLE ROW LEVEL SECURITY;
ALTER TABLE attendance DISABLE ROW LEVEL SECURITY;
ALTER TABLE leaves DISABLE ROW LEVEL SECURITY;
ALTER TABLE loans DISABLE ROW LEVEL SECURITY;
ALTER TABLE payroll_rules DISABLE ROW LEVEL SECURITY;
ALTER TABLE employee_payroll_rules DISABLE ROW LEVEL SECURITY;
ALTER TABLE payslips DISABLE ROW LEVEL SECURITY;
ALTER TABLE companies DISABLE ROW LEVEL SECURITY;
